- CONTRIBUTING.md
> CONTRIBUTING: add instructions for pull requests

- idtoken/validate.go
- idtoken/validate_test.go
> idtoken: validate if token is expired

- CONTRIBUTING.md
Make commit message style clearer.
> CONTRIBUTING: improve readability

- synth.py
> internal: fix pathing to script

- idtoken/validate.go
- idtoken/validate_test.go
Unmarshal all claims into Payload.Claims.
Fixes #497.
> idtoken: populate Claims map

- internal/kokoro/synth/synth.sh
> internal/kokoro: fix typo in script

- go.mod
- tools.go
This is now baked into the kokoro image.
> chore(all): remove direct dependency on honnef.co/go/tools

- .github/renovate.json
> chore(.github): automate dependency updates with Renovate

- .github/renovate.json
Try changing config so a PR should open right away.
> chore: try to get renovate going

- .github/renovate.json
- go.mod
- go.sum
These are now unfrozen since min compat is now 1.15
> feat: bump grpc and x/net

- apigee/v1/apigee-api.json
- apigee/v1/apigee-gen.go
- bigquery/v2/bigquery-api.json
- bigquery/v2/bigquery-gen.go
- monitoring/v1/monitoring-api.json
- monitoring/v1/monitoring-gen.go
- monitoring/v3/monitoring-api.json
- monitoring/v3/monitoring-gen.go
For whatever reason our nightly job has not picked up a few local
changes. Ran "make all" locally to get things generated and changes
picked-up.
> feat: manual regen

- internal/kokoro/test.sh
Adapted from [google-cloud-go/kokoro/continuous.sh](https://github.com/googleapis/google-cloud-go/blob/main/internal/kokoro/continuous.sh#L168-L173).
closes: #1321
> chore: add flakybot

- go.mod
- go.sum
> fix: upgrade version of golang.org/x/net

- googleapi/googleapi.go
> feat(googleapi): add response headers to Error from CheckMediaResponse

- internal/kokoro/vet.sh
> chore(all): update vet.sh to go runtime 1.20

- google-api-go-generator/testdata/any.want
- google-api-go-generator/testdata/arrayofarray-1.want
- google-api-go-generator/testdata/arrayofenum.want
- google-api-go-generator/testdata/arrayofmapofobjects.want
- google-api-go-generator/testdata/arrayofmapofstrings.want
- google-api-go-generator/testdata/blogger-3.want
- google-api-go-generator/testdata/floats.want
- google-api-go-generator/testdata/getwithoutbody.want
- google-api-go-generator/testdata/http-body.want
- google-api-go-generator/testdata/json-body.want
- google-api-go-generator/testdata/mapofany.want
- google-api-go-generator/testdata/mapofarrayofobjects.want
- google-api-go-generator/testdata/mapofint64strings.want
- google-api-go-generator/testdata/mapofobjects.want
- google-api-go-generator/testdata/mapofstrings-1.want
- google-api-go-generator/testdata/param-rename.want
- google-api-go-generator/testdata/quotednum.want
- google-api-go-generator/testdata/repeated.want
- google-api-go-generator/testdata/required-query.want
- google-api-go-generator/testdata/resource-named-service.want
- google-api-go-generator/testdata/unfortunatedefaults.want
- google-api-go-generator/testdata/variants.want
- google-api-go-generator/testdata/wrapnewlines.want
> test: update test due to generator change

- option/internaloption/internaloption.go
- option/internaloption/internaloption_test.go
> docs(option): update WithDefaultEndpointTemplate docs

- internal/cba.go
- internal/cba_test.go
don't enable s2a if an override endpoint is set, since we don't know if the endpoint is mtls-capable or not
> fix(transport): not enable s2a when there is endpoint override

- transport/grpc/dial.go
- transport/http/dial.go
Tested with google-cloud-go go mod replacing the dep.
> fix: default defaultEndpointTemplate

- internal/creds.go
- internal/settings.go
> fix: check []bytes > 0 instead of nil

- bigquery/v2/bigquery-gen.go
- compute/v0.alpha/compute-gen.go
- compute/v0.beta/compute-gen.go
- compute/v1/compute-gen.go
- google-api-go-generator/gen.go
- storage/v1/storage-gen.go
This reverts commit 66ace6c95689fd06cb467069d8ec0f5ddb8ac695.
> revert: move storage, bigquery, and compute to new auth lib (#2695)"

- doc.go
- go.mod
- go.sum
- go.work.sum
I believe our dep cycle issues should have been fixed in #2907.
Verified issue in #2543 is fixed with this change.
Fixes: #2559
> fix: remove dep hacks for old cycle deps

- support/bundler/bundler_test.go
> test(support/bundler): increase context timeout to avoid occasional test failures
