googleapis/google-api-go-client

internal/kokoro/synth/sendpr/sendpr.go, internal/kokoro/synth/synth.sh
#489 had code that didn't compile (whoops), but strangely didn't get picked up by tests.
=> internal/kokoro/synth: fix compilation errors

google-api-go-generator/gen.go
This should no longer be an issue to generate now that we make sure we only re-generate newer revisions.
Fixes: #471
=> internal: re-enable generation of customsearch

transport/grpc/dial.go
This will swap "foo.googleapis.com" to "foo.mtls.googleapis.com" and used by mtls_smoketest.
=> transport/grpc: support GOOGLE_API_USE_MTLS=always

transport/grpc/dial.go
dial is called multiple times when connection pooling is used,
and reassigning o.Endpoint multiple times generated endpoints like:
pubsub.mtls.mtls.googleapis.com
=> transport/grpc: don't reassign ClientSettings.Endpoint

internal/kokoro/synth/synth.sh
These are nice to have in general. Trying to debug why this script
is updating the go.mod. See #594 as an example PR that is not
right.
Updates: #590
=> chore(internal/kokoro): add Go info to build logs

internal/kokoro/vet.sh
This is already present in the image. This is currently causing
some CI failures. See #603 as an example.
=> fix(internal/kokoro): remove install of staticcheck

internal/kokoro/synth/synth.sh
Unable to remove currently installed verision in this environment.
Instead, install in user home and add that to PATH.
=> chore(internal/kokoro): fix Go install

internal/kokoro/synth/synth.sh
It seems like the build environment has GOROOT explicitly set to
`/usr/local/go`. `go build` returns the following compiler error:
compile: version "go1.12" does not match go tool version "go1.15.1"
=> chore(internal/kokoro): set GOROOT for synth

internal/settings.go, option/internaloption/internaloption.go, transport/grpc/dial.go, transport/grpc/dial_socketopt_test.go, transport/grpc/dial_test.go
We want to make bigtable yoshi library to attempt DirectPath by default, instead of checking the environment variable GOOGLE_CLOUD_ENABLE_DIRECT_PATH. Notice that even after this PR, the real datapath is still CFE since ACL is currently denied for all projects.
Relevant Bigtable client library PR link: https://github.com/googleapis/google-cloud-go/pull/3116.
=> feat(internaloption): add EnableDirectPath internaloption 

.github/CODEOWNERS
This is needed so that the stamp it gives counts as having a
CODEOWNER review the change.
=> chore(.github): add auto-approve bot to codeowners

internal/creds.go
This was recently caught by the spanner team. This is a part of the spec.
=> fix(internal): don't self-sign JWT when an endpoint provided

impersonate/doc.go, impersonate/example_test.go, impersonate/idtoken.go, impersonate/idtoken_test.go, impersonate/impersonate.go, impersonate/impersonate_test.go, impersonate/integration_test.go, impersonate/user.go, impersonate/user_test.go, internal/kokoro/test.sh, option/option.go
This package is used for creating a impersonated TokenSource. This
TokenSource can then be passed into any client or API that accepts
a client option. This package provides support for three types of
impersonation:
1. A service account impersonating another service account.
2. A service account impersonating another service account as an
admin user -- a pattern used with domain wide delegation.
3. A service account creating an impersonated ID token.
Fixes: #652
Fixes: #777
Fixes: #731
Updates: #378
=> feat: add impersonate pacakge

CHANGES.md
This commit will be tagged v0.44.0-impersonate-preview.
=> chore: release v0.44.0-impersonate-preview

google-api-go-generator/gen.go
This is already the case in both the beta and v1 surface.
=> fix(compute): make MetadataItems.Value a pointer

.github/renovate.json
Currently the tidying on the renovate PRs is never correct as we expect
it to be tidied to 1.16 standards. According to 
https://github.com/renovatebot/renovate/issues/6213 this should make
sure we are using version 1.16
=> chore: try to use correct version of Go

transport/http/configure_http2_go116.go
Increase this value to comply with CFE rate limit on pings.
Closes googleapis/google-cloud-go#4121
=> fix(transport): increase ReadIdleTimeout

transport/internal/dca/dca.go
The terraform CLI requires this change in order to support mTLS.
For existing users that provide custom http clients today, this change is invisible since it is gated by the mTLS environment variable.
=> fix(transport): Perform mtls endpoint switching with custom http client

internal/creds.go
Removed the requirement on length of scopes passed. Checking the EnableJwtWithScope internal option should be sufficient since it will only be passed with our generated clients that will always include at least the platform scope and a default audience. 
Fixes: #1092
=> fix(internal): fix self-signed detection with scopes

idtoken/validate.go
When NewValidator is called without any options passed in it will
fail talking to the google cert endpoint because the dailed
authenticated client will not have proper scopes and leads to the
error: "invalid_scope". We should set a default scope do this method
can be called with no extra options.
Fixes: #1187
=> fix(idtoken): provide default scope for cert endpoint

transport/grpc/dial.go
Follow https://github.com/grpc/grpc-go/pull/5044 to update the xds scheme for DirectPath.
=> transport: update xds  directpath xds scheme

go.mod, internal/gensupport/send.go, internal/gensupport/send_test.go
This change makes it deterministic to call SendRequestWithRetry with a
canceled context. This is going to be useful because some Cloud APIs
rely on the context being canceled to prevent some operations from
proceeding, like
[`storage.(*ObjectHandle).NewWriter`](https://pkg.go.dev/cloud.google.com/go/storage#ObjectHandle.NewWriter).
Fixes: #1358
=> fix(internal/gensupport): Make SendRequestWithRetry check for canceled contexts twice

examples/customsearch.go
fix: Adding import references in examples/customsearch
Missing alias for the `customsearch` import statement will cause its references to raise errors. This type of package reference is also found in every other example, with similar import statements (`{package}/{version}`)
=> fix: Adding import references in examples/customsearch

go.mod, googleapi/googleapi.go, internal/gensupport/media.go, internal/gensupport/media_test.go, internal/gensupport/resumable.go, internal/gensupport/resumable_test.go, internal/gensupport/retry.go
feat(gensupport): per-chunk deadline configs
Allow users to configure the per-chunk deadline for retries
that's used during resumable uploads.
Needs to be exposed via the manual layer for storage.
Fixes #685
=> feat(gensupport): per-chunk deadline configs

googleapi/googleapi.go, googleapi/googleapi_test.go
Currently googleapi.Error is not populating the Header field with
response headers. We found this to be true across multiple APIs.
This fix ensures that Header is filled in correctly, allowing
easier debugging by callers.
=> fix(googleapi): fill response headers in Error

internal/gensupport/resumable.go
Fix an edge case that I noticed when testing a very small
ChunkRetryDeadline via the storage client. If the user
chooses a deadline too short to send a single request for the
chunk, we cause a failure so that resp and err are not
both nil.
=> fix(gensupport): cover ChunkRetryDeadline edge case

internal/kokoro/discogen.sh
This will be called from a cron job. Script should land before
backing config. Related cl: 427492527
=> chore: add a script that invoke regen

internal/kokoro/discogen/main.go
Adding some info to try to debug this block of failing bash.
=> chore(internal/kokoro): add more debug info

transport/grpc/dial.go
Add an environment variable `GOOGLE_CLOUD_DISABLE_DIRECT_PATH` to disable DirectPath. We expect users to use the [EnableDirectPath option](https://github.com/googleapis/google-api-go-client/blob/main/option/internaloption/internaloption.go#L60) to control DirectPath for most cases, and this environment variable is for special cases like running both DP and GFE traffic on the same VM. As a result, only when this env variable is explicitly set to `true` will DirectPath be disabled.
Same PR for Java: https://github.com/googleapis/gax-java/pull/1412.
=> feat(transport): add an env variable to disable DirectPath

internal/gensupport/retry.go
Fixes googleapis/google-cloud-go/issues/5704
=> feat(internal/gensupport): add net.ErrClosed to default retry

option/option.go
A customer noticed this comment in the documentation and became concerned about future support. Since this comment & feature have been in the library for > 6 years, can we get rid of the comment?
=> docs: removed stale comment

cloudcommerceprocurement/v1/cloudcommerceprocurement-api.json, cloudcommerceprocurement/v1/cloudcommerceprocurement-gen.go
This is an out-of-band update as this API is no longer listed on the
public discovery index.
=> feat: regen cloudcommerceprocurement v1

idtoken/idtoken.go
Should be "The token will have the audience...", I think.
=> docs(idtoken): fix a typo on `NewClient` method

google-api-go-generator/gen.go
Added field PaymentState of schema SubscriptionPurchase of the androidpublisher:v3 api to the list of pointerFields. This was done the same way as it was previously done for v2.
Fixes #727
=> feat(google-api-go-generator): Change field PaymentState to pointer

option/option.go
Clarify that when both WithScopes and WithTokenSource are used, the
scope settings will be taken from the token source and the WithScopes
option will be ignored.
Fixes #1644
=> docs(option): clarify behavior of WithScopes

option/option.go
This option has been soft deprecated for a long time now. Lets make
it official to help more users migrate.
=> feat(option): officially deprecate ImpersonateCredentials

internal/gensupport/send.go
I have a use case in which my context is cancelling a `sendAndRetry()` operation, and the error being returned is the error returned by the Google API in the previous attempt of `sendAndRetry()` instead of `ctx.Err()`, which is misleading because I was investigating why the Google Storage Go library was giving up on a 503 error (which is not expected according to the retry/idempotency docs: https://cloud.google.com/storage/docs/retry-strategy).
closes: #1685
=> feat(internal/gensupport): wrap retry failures with context and prev error

transport/grpc/pool_test.go
This pull request fixes arg for test failure logs in `transport/grpc/pool_test.go`
=> test(transport/grpc): fix arg for test failure logs

go.mod, transport/grpc/dial_socketopt.go, transport/grpc/dial_socketopt_test.go
We only referenced a constant, so I inlined it.
=> feat: rm hard dep on x/sys

idtoken/idtoken.go
=> fix(idtoken): increase MaxIdleConnsPerHost to 100 in NewClient

transport/grpc/dial.go
For **gRPC**, this separates the logic for _credential_ dial options (associated with the `WithoutAuthentication` option) from the _connection-level encryption_ dial options (associated with the `WithInsecure` option OR using `DialInsecure`). This allows a _secure_ connection to be dialed _without_ credentials.
Previously, using `WithoutAuthentication` alone (i.e. without `WithInsecure` or `grpc.WithTransportCredentials(credentials.NewTLS(nil))`, and while using `Dial`) would result in attempting to dial a secure connection but without any credentials **or** TLS config, resulting in an error. For example, the following code returns an error:
```go
c, err := grpc.Dial(context.Background(),
option.WithEndpoint("storage.googleapis.com:443"),
option.WithoutAuthentication())
if err != nil {
// …
```
=> fix(transport/grpc): separate options for creds and certs

transport/grpc/dial.go
grpc-go change: https://github.com/grpc/grpc-go/blob/master/xds/googledirectpath/googlec2p.go#L51
@apolcyn
=> feat(transport): de-experiment google-c2p resolver

.github/renovate.json
Related to googleapis/google-cloud-go#7117
=> chore: ignore some golang.org/x/* dependencies in renovate

go.mod, go.sum, internal/gensupport/send_test.go
go1.13 and up now provide this functionality, and the xerrors.Is() function was deprecated.
Removing the dependency, as it was only used in a test.
=> chore: remove uses of obsolete golang.org/x/xerrors

internal/gensupport/json.go, internal/gensupport/json_test.go
Previous impl assumed maps would be of type map[string]string. Although this is most of the map types this library uses some use more complex types. For these cases it is impossible to unset fields in patch requests until this fix. Reported internal
Ref: b/261221901
=> feat: support set null map entries for non-simple map values

google-api-go-generator/gen.go
I have emailed the support channels and restore this API once it starts having a valid format again.
=> chore: skip generating integrations:v1 as it fails generation

integration-tests/byoid/integration_test.go
This helps account for skew and timing issues.
Fixes: #1783
=> test: add buffer to both sides of token expiry validation

internal/gensupport/resumable.go
quitAfterTimer should only be closed when function breaks or returns as it is created outside of the for loop. Tested with local replacing and fixes failing TestIndefiniteRetries test with the patch.
Fixes: https://github.com/googleapis/google-cloud-go/issues/7410
=> fix(internal/gensuport): don't prematurely close timers

google-api-go-generator/gen.go
In case the auto-generated codes do not.
Fixes #1908
=> fix: always reference the internal package.

go.mod, go.sum
it fixes a target naming issue when using bazel/gazelle
=> chore(deps): update s2a-go to v0.1.1

androidmanagement/v1/androidmanagement-gen.go, bigquery/v2/bigquery-gen.go, chromeuxreport/v1/chromeuxreport-gen.go, cloudsearch/v1/cloudsearch-gen.go, dataflow/v1b3/dataflow-gen.go, dataplex/v1/dataplex-gen.go, discoveryengine/v1alpha/discoveryengine-gen.go, discoveryengine/v1beta/discoveryengine-gen.go, google-api-go-generator/clients_test.go, google-api-go-generator/gen.go, google-api-go-generator/testdata/json-body.want, google-api-go-generator/testdata/variants.want, integrations/v1alpha/integrations-gen.go, jobs/v3/jobs-gen.go, jobs/v3p1beta1/jobs-gen.go, logging/v2/logging-gen.go, migrationcenter/v1alpha1/migrationcenter-gen.go, ml/v1/ml-gen.go, monitoring/v3/monitoring-gen.go, recommendationengine/v1beta1/recommendationengine-gen.go, retail/v2/retail-gen.go, retail/v2alpha/retail-gen.go, retail/v2beta/retail-gen.go, servicecontrol/v1/servicecontrol-gen.go, spanner/v1/spanner-gen.go, vision/v1/vision-gen.go, vision/v1p1beta1/vision-gen.go, vision/v1p2beta1/vision-gen.go
Just like normal floats our arrary of floats should be able to
handle things like "NaN".
Fixes: https://github.com/googleapis/google-api-go-client/issues/1970
=> fix: add better support of array of floats

.github/workflows/autoapprove.yml
Changes AutoApprove to target PRs from the `discogen` branch.
Adds explicit workflow permissions.
Fixes #1980
=> chore(ci): fix AutoApprove for discogen

.github/workflows/autoapprove.yml
The [docs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) don't indicate what `permissions` would apply to fixing the [`createReview` issue](https://github.com/googleapis/google-api-go-client/actions/runs/5011498932/jobs/8982392653?pr=1982). But I'm also not sure if these perms actually apply to the `YOSHI_APPROVER_TOKEN` used for all of the API calls.
This should be temporary until we find the right perms.
=> chore: temporarily give AutoApprove job full write

.github/CODEOWNERS, .github/auto-approve.yml
Enables the new `GoApiaryCodegen` config with `auto-approve` to approve the Apiary/Discovery regeneration PRs like [this](https://github.com/googleapis/google-api-go-client/pull/1982).
=> chore: enable GoApiaryCodegen auto-approve

go.mod, go.sum
This updates google.golang.org/genproto to a version that introduces submodules for commonly used generic packages (api, rpc, etc) so that they can be used without taking dependencies on cloud packages in the future. For more information, please see googleapis/go-genproto#1015.
=> chore(all): update google.golang.org/genproto to submodules

google-api-go-generator/gen.go
Restore this API once the ExecuteEvent RPC definition is valid. See internal issue b/286436239.
=> chore: skip generating integrations:v1alpha as it fails generation

google-api-go-generator/gen.go
refs: #2014
Comment on b/286436239 from Integrations team: "I have reverted the change that is expected to cause this break".
=> chore: restore generating integrations:v1alpha

google-api-go-generator/gen.go
refs: #2037
refs: #2014
Unfortunately, reinstating `integrations/v1alpha` broke the build again. Therefore I will revert PR #2037 and skip it again in the generation.
```
2023/06/26 07:09:48 Generating API integrations:v1alpha
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x6c06c7]
goroutine 1 [running]:
main.(*Method).NewBodyArg(0xc0004674a0?, 0xc02b641590)
/tmpfs/src/github/google-api-go-client/google-api-go-generator/gen.go:2437 +0x27
main.(*Method).NewArguments(0xc0001fdc20)
/tmpfs/src/github/google-api-go-client/google-api-go-generator/gen.go:2430 +0x297
main.(*Method).generateCode(0xc0001fdc20)
/tmpfs/src/github/google-api-go-client/google-api-go-generator/gen.go:1835 +0x236 …
```
=> chore: skip generating integrations:v1alpha

internal/cba.go, internal/cba_test.go
add a couple more checks before using S2A for mtls
1. make sure `DefaultMTLSEndpoint` is not empty
2. skip s2a if custom http client is provided, because there's no guarantee the client passed in is mtls-capable
=> feat: additional checks before using S2A

internal/kokoro/discogen.sh
From our logs:
```
go build -o google-api-go-generator
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
unable to generate discovery clients: exit status 2
```
=> chore: fix discogen

internal/kokoro/discogen.sh
This issue was a symptom of an underlying problem. Trying to root cause this by rolling back to original behaviour
=> chore: remove added build flag for discogen

internal/settings.go, option/internaloption/internaloption.go
We will use the internaloption to start to enable new auth lib for a small number of clients in the future. The envvar will be undocumented and used exclusively in our own testing environments. We will enable it on all of our repos as the first part of functional testing that all existing integration tests continue to work as normal when routing through the new auth layers.
=> feat(internal): add some feature flags for new auth libs

doc.go
=> fix(docs): add an operation polling example

transport/grpc/dial.go, transport/grpc/dial_test.go
* Memoize otelgrpc.NewClientHandler for reuse
fixes: #2321
=> fix(transport): fix memory leak in grpc.Dial

transport/grpc/dial.go, transport/grpc/dial_test.go
Fixes https://github.com/googleapis/google-api-go-client/issues/485
=> feat(transport): add support for API keys for gprc

.github/renovate.json
"properly" ignore `github.com/google/go-github` dependency updates via renovate since they require code changes (import path updates). Since the module name is changed with each release, we cannot `ignoreDeps` a single module, and [`ignoreDeps` does not support pattern matching, but has a workaround](https://docs.renovatebot.com/configuration-options/#ignoredeps), which I've implemented here.
=> chore(deps): ignore google/go-github package updates

internal/settings.go
=> fix(transport): return GDU for all errors from MDS universe_domain

idtoken/integration_test.go, internal/creds.go
Also updated a test that relied on impl specific types before. Testing the TokenSource methods instead of NewClient as NewClient defers impl to NewTokenSource anyways.
Fixes: #2523
Fixes: #2522
=> fix(internal): set scopes for new auth flow

go.mod, go.sum, go.work.sum, transport/grpc/dial.go, transport/grpc/pool.go, transport/http/dial.go
- Better support for oauth2.Credential conversion
- set quota project when setting tokensource based cred
- honor SkipValidation option
- if DefaultEndpointTemplate is not set pass old DefaultEndpoint. As we just do a string replace code works without formatting derective present.
- simiplfiy poolAdapter calls to delegate more
=> fix: various auth transition bugs

.github/renovate.json
Fixes incorrect renovate config field `matchingPackageNames` -> `matchingPackagePatterns`.
Disables otel instrumentation updates b.c they require Go 1.21.
=> chore(deps): disable otel updates until Go 1.21

internal/gensupport/resumable.go
This makes it easier to debug whether and/or how many retries happened before a failure with a chunk upload.
=> fix(gensupport): wrap chunk upload err for retries

transport/grpc/dial.go, transport/grpc/dial_test.go
The only code that converted the `option.WithUserAgent` to a gRPC DialOption `WithUserAgent` was in the `dial` function, which was bypassed when leveraging the new auth library that handles most of the important dialing set up re:credentials.
To fix this, I added a new helper specifically for use in `dialPoolNewAuth` that prepares dial options based on the given `DialSettings` - `prepareDialOpionsNewAuth`. I could've added the same logic to anywhere in `dialPoolNewAuth` to fix it, but I felt I needed to signal that this is the method to be modifying gRPC DialOptions in so that in the future, we can centralize further gRPC DialOption manipulation rather than just "wherever" like in the "old" `dial`.
Also stored the `grpctransport.Dial` function into a global variable so that unit tests …
=> fix(transport/grpc): retain UserAgent option with new auth stack

bigquery/v2/bigquery-gen.go, compute/v0.alpha/compute-gen.go, compute/v0.beta/compute-gen.go, compute/v1/compute-gen.go, google-api-go-generator/gen.go, storage/v1/storage-gen.go
All other clients in this repo have been exercising the new library
for almost 3 months now. I believe things to be stable so we should
move the remaining libraries.
=> feat: move storage, bigquery, and compute to new auth lib

google-api-go-generator/gen.go, storage/v1/storage-gen.go
The storage client is the only client that imports gax. Depending on the RPCs being generated it may or may not use the gax import. To avoid generating an unreferenced lets always import it.
Internal Question: 9036645275644461056
=> fix: reference gax import in storage libs

internal/creds.go
Making the same change as #2684 in the internal/creds.go file since it is called by the storage library.
=> fix(cba): Update credsNewAuth path to use nil oauth2 client

google-api-go-generator/gen.go, monitoring/v1/monitoring-gen.go
=> fix(gen): change HttpBody.Data from string to any for monitoring:v1

transport/grpc/dial.go, transport/grpc/dial_test.go, transport/http/dial.go
* Set value when GOOGLE_API_GO_EXPERIMENTAL_ENABLE_NEW_AUTH_LIB=true
=> fix(transport): set UniverseDomain in http.NewClient for new auth

internal/gensupport/resumable.go
Previously, if an rCtx wasn't created with chunkTransferTimeout and the parent context had a timeout, calling cancel under the same conditions caused a crash due to invalid memory access. This occurred if the parent context's timeout was triggered.
=> fix(gensupport): context cancel error check

go.mod, go.sum, idtoken/idtoken.go, internal/creds.go, transport/grpc/dial.go, transport/http/dial.go
This connects the logger passed in by users with options to the auth library.
=> feat: pass through logger in options

transport/grpc/dial.go
Copy the new field AllowHardBoundTokens from the user options to the internal options in the new auth. The option was added in PR: https://github.com/googleapis/google-api-go-client/pull/2975
=> fix: Copy AllowHardBoundTokens option from old auth to new auth.

transport/http/dial.go
=> fix(transport/http): Add user agent to request headers

googleapi/googleapi.go, googleapi/googleapi_test.go
fixes: googleapis/gax-go#389
```
R.......R......R.....R.......R......R......R.....R.......R.......R.......R
2025/03/20 15:59:31 googleapi: Error 429: Resource has been exhausted (e.g. check quota).
```
=> fix(googleapi): add JSON array support to CheckResponseWithBody

internal/settings.go
If a user explicitly sends in a new auth credential we should use it in the context of our new auth stack as the older transports don't respect the AuthCredential dial setting.
Internal Bug: 419103794
=> fix: check for auth creds in options to trigger new auth lib usage

idtoken/idtoken.go
=> fix(idtoken): don't assume DefaultTransport is a http.Transport
